#!/bin/bash
#
# Launch gnome-terminal.
# If it's already running, switch to that window.
# If it's the current window, minimize it.
# Bind to a keyboard shortcut (e.g., ctrl+`) for quick access a la Quake HUD.

windows=`xdotool search --name 'Terminal HUD'`

if [[ -z "$windows" ]] ; then
    gnome-terminal --full-screen --hide-menubar --profile=hud
    sleep 1
    wmctrl -F -r 'Terminal HUD' -b add,sticky
    exit
fi

active=`xdotool getactivewindow`

for window in $windows; do
    if [ "$window" -eq "$active" ] ; then
        xdotool windowminimize $window
        exit
    fi
done

xdotool windowactivate $window
