#!/bin/bash
#
# Usage: pushbullet <command>
#
# Execute a command and push a notification to Pushbullet when it finishes.
# You need to save your Pushbullet API token in ~/.pushbullet

tokenfile="$HOME/.pushbullet"
if [ ! -e "$tokenfile" ] ; then
    CLIENT_ID=fpYTsqYDG8GYQg1PkndrZ4JZPKV39egi
    #REDIRECT_URI="https%3A%2F%2Fgithub.com%2Fesamson%2Futility-belt%2Fblob%2Fmaster%2Fpace?tokenfile=$tokenfile"
    REDIRECT_URI="http%3A%2F%2Fapps.samson.ph%2Fpace%3Ftokenfile%3D$tokenfile"
    OAUTH_URL="https://www.pushbullet.com/authorize?client_id=$CLIENT_ID&redirect_uri=$REDIRECT_URI&response_type=token&scope=everything"
    echo
    echo "Pushbullet API token not found in $tokenfile"
    echo
    echo "Authorize pace at $OAUTH_URL"
    echo
    echo "The API token will be in the access_token fragment of the URI you are redirected to."
    echo "Save that token in $tokenfile"
    xdg-open "$OAUTH_URL"
    exit 1
fi
token="$(<$tokenfile)"

COMMAND=$*
echo $COMMAND

START=$(date +"%s")
(eval $COMMAND)
END=$(date +"%s")
SECONDS=$(($END-$START))
TIME="$(($SECONDS / 60)) min $(($SECONDS % 60)) sec"

EXITCODE=$?
if [ $EXITCODE -eq 0 ] ; then
    curl -u $token: https://api.pushbullet.com/v2/pushes -d type=note -d title="$1 SUCCESS ($TIME)" -d body="$COMMAND" > /dev/null 2>&1 &
else
    curl -u $token: https://api.pushbullet.com/v2/pushes -d type=note -d title="$1 FAIL ($TIME)" -d body="$COMMAND" > /dev/null 2>&1 &
fi

