#!/bin/bash

DIR=~/Downloads
LOG=$DIR/.purge.log

echo "===== $(date) =====" >> $LOG
echo "Purging old entries in $DIR" >> $LOG
echo >> $LOG

find $DIR -mindepth 1 -maxdepth 1 -ctime +7 >> $LOG
(time find $DIR -mindepth 1 -maxdepth 1 -ctime +7 -exec rm -rf "{}" \;) >> $LOG 2>&1
echo >> $LOG
