#!/bin/bash
#
# Usage: pushbullet <command>
#
# Execute a command and push a notification to Pushbullet when it finishes.
# You need to save your Pushbullet API token in ~/.pushbullet

tokenfile="$HOME/.pushbullet"
if [ ! -e "$tokenfile" ] ; then
    echo "Pushbullet API token not found in $tokenfile"
    exit 1
fi
token="$(<$tokenfile)"

COMMAND=$*
echo $COMMAND

START=$(date +"%s")
(eval $COMMAND)
END=$(date +"%s")
SECONDS=$(($END-$START))
TIME="$(($SECONDS / 60)) min $(($SECONDS % 60)) sec"

EXITCODE=$?
if [ $EXITCODE -eq 0 ] ; then
    curl -u $token: https://api.pushbullet.com/v2/pushes -d type=note -d title="$1 SUCCESS ($TIME)" -d body="$COMMAND" > /dev/null 2>&1 &
else
    curl -u $token: https://api.pushbullet.com/v2/pushes -d type=note -d title="$1 FAIL ($TIME)" -d body="$COMMAND" > /dev/null 2>&1 &
fi

