#!/bin/bash

# resolve links - $0 may be a softlink
PRG="$0"
 
while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
 
PRGDIR=`dirname "$PRG"`
BASEDIR=`cd "$PRGDIR" >/dev/null; pwd`

SCRIPTS_DIR="$BASEDIR/pdv-demo-scripts/"
BUILD_DIR=`mktemp -d`
DEMO_DIR=$HOME/.local/share/Dropbox/PDV/demo/
SWAN_DIR=$HOME/code/swan
SEAGULL_DIR=$HOME/code/seagull

cd $SWAN_DIR \
    && mvn clean install \
    && cp $SWAN_DIR/Vagrantfile $BUILD_DIR \
    && cp $SWAN_DIR/swan-server/dev.yaml $BUILD_DIR \
    && cp $SWAN_DIR/swan-server/src/test/resources/device.keystore $BUILD_DIR \
    && cp $SWAN_DIR/swan-server/target/swan-server-1.0.0-SNAPSHOT.jar $BUILD_DIR/swan-server.jar \
&& \
cd $SEAGULL_DIR \
    && mvn clean install \
    && cp $SEAGULL_DIR/seagull-app-g/target/seagull-app-g-1.0.0-SNAPSHOT.jar $BUILD_DIR/seagull-app-g.jar \
&& \
rsync -a $SCRIPTS_DIR $BUILD_DIR \
&& rsync -av --delete $BUILD_DIR/ $DEMO_DIR \
&& rm -rf $BUILD_DIR

