#!/bin/bash

SWAN_DIR=~/code/swan
SWAN_SERVER=$SWAN_DIR/swan-server
export DEVICE_KEYSTORE_FILE=$SWAN_SERVER/src/test/resources/device.keystore
export DEVICE_KEYSTORE_PASSWORD=`cat "$DEVICE_KEYSTORE_FILE.password"`
export SERVER_KEYSTORE_FILE=$SWAN_SERVER/src/test/resources/swan.keystore
export SERVER_KEYSTORE_PASSWORD=`cat "$SERVER_KEYSTORE_FILE.password"`

cd $SWAN_SERVER
java -jar -Dtestmode target/swan-server-1.0.0-SNAPSHOT.jar server test.yaml

